### ISSUE TITLE
Cannot start

### ISSUE THREAD

**Issue by kakitone** [jupyter/colaboratory#119]
I get the following error message. Not sure what happens. But I followed the instructions exactly.

(venv)kakitone:colaboratory kakitlam$ python -m colaboratory
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/kakitlam/codelabkk/colaboratory/colaboratory/__main__.py", line 11, in <module>
    launch_new_instance()
  File "/Users/kakitlam/codelabkk/venv/lib/python2.7/site-packages/IPython/config/application.py", line 573, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "/Users/kakitlam/codelabkk/venv/lib/python2.7/site-packages/IPython/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "colaboratory/colaboratory.py", line 509, in initialize
    self.init_configurables()
  File "colaboratory/colaboratory.py", line 355, in init_configurables
    kls = import_item(self.notebook_manager_class)
  File "/Users/kakitlam/codelabkk/venv/lib/python2.7/site-packages/IPython/utils/importstring.py", line 42, in import_item
    module = __import__(package, fromlist=[obj])
ImportError: No module named notebooks.filenbmanager

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True

**Comment by kakitone** [comment]
Oops. i got it. I have to uninstall ipython3 and then install back ipython2.3 even when i am in a brand new virtual env. I guess you may want to add a note to that... anyway, great work...
